### ISSUE TITLE
Format for `pred_joints` data preparation

### ISSUE THREAD

**Issue by purvaten** [jyunlee/Im2Hands#2]
Hi,

For Step 4 of the [Data Preparation](https://github.com/jyunlee/Im2Hands#data-preparation) section, could you please let me know the desired format for 3D hand joint positions? I am using GT InterHand2.6M data which is in [this format](https://github.com/facebookresearch/InterWild/blob/bec2821700dfc4423327b3209e3c46724a0c9ae1/data/InterHand26M/InterHand26M.py#L35).

If my understanding is correct, I need to save it in the reverse format for each hand, starting with wrist, Pinky1, Pinky2, Pinky3, Pinky4, Ring1, etc. in a `.ply` file. Could you please confirm?

Thank you.

**Comment by jyunlee** [comment]
Hello, thanks for your interest in our work. 
I used 3D hand joint positions starting with wrist, thumb1, thumb2, thumb3, thumb4, index1, etc - which is in the non-reverse format.
For your reference, I also attached sample [`.ply` files](https://drive.google.com/drive/folders/1LJV4WW_5KzGAB4r1Czo9UkRYf0KOGcYW?usp=sharing) used in my experiments. (The attached `left.ply` and `right.ply` examples are not the paired ones though.)
Please let me know if you have more questions!

**Comment by purvaten** [comment]
Perfect, thank you for the prompt response!
